---
# tasks file for deploy_be_simple
- name: install packages
  apt:
    name: ['python3-pip', 'git', 'postgresql', 'postgresql-contrib', 'libpq-dev', 'python3-psycopg2']
    state: latest
    update_cache: yes
- set_fact: ansible_python_interpreter=/usr/bin/python3

- name: create db
  postgresql_db:
    name: app
  become_user: postgres
- name: create db user
  postgresql_user:
    db: app
    name: worker
    password: worker
    role_attr_flags: SUPERUSER
  become_user: postgres
- name: set owner db app
  postgresql_owner:
    db: app
    new_owner: worker
  become_user: postgres
- name: postgresql enable service
  systemd:
    name: postgresql
    enabled: yes
    state: restarted
